portfolio-project-setup and mobile first
bekure27/project-1-portfolio pull request #1
Opened 2022-08-17 22:40 UTC by bekure27

add **header** and **headline** sections with necessary styling

2022-08-17 22:57 UTC, phelian23 reviewed
Hi @bekure27, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is failing in some linter checks. Kindly fix it and resubmit for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-08-18 04:48 UTC, levy002 requested changes
## Hello @bekure27   , :wave:
### I'm Levy, your PR reviewer

Magnificent job :sunglasses: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
-  Linters are green :heavy_check_mark: 
- Well structured and clean code :heavy_check_mark: 
- Nice design :heavy_check_mark: 
- Correct usage of Github flow :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._
    
- [x] Kindly make sure to add a good PR title and PR description. It makes your repo looks more professional. :wink:  You can go ahead and edit your PR to make it descriptive.

   - Example of good PR
![image](https://user-images.githubusercontent.com/87197412/184990532-da778ab4-c789-4136-90a9-629eedd969da.png)
   
     
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to write your commit message in imperative tense and capitalized. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 04:48 UTC, levy002 commented on index.html
> +            <li><p class="p-name">Bekure</p></li>
- [ ] Kindly make sure to your logo into an `a` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-08-18 04:48 UTC, levy002 commented on index.html
> +            <li><a href="#" class="toggle-menu"><img src="icons/menu_icon.png" alt=""></a></li>
- [ ] Kindly wrap The hamburger button in a `nav` tag for correct usage of semantics which will increase our website accessibility.

2022-08-18 04:48 UTC, levy002 commented on index.html
> +  <div class="headline">
-[ ] Kindly wrap this headline section into `section` while it represents a generic standalone section on the document. This way will be semantically correct and will increase website accessibility for screen readers and other technologies. For more information about this check [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) :wink:

2022-08-18 04:48 UTC, levy002 commented on index.html
> +        I’m Bekure</p>
- [ ] Kindly change this `p` to `h1` as this is the main heading on the page it should be wrapped into `h1` tag. For more information about this heading please check [here](https://www.reliablesoft.net/h1-tag/).

2022-08-18 04:48 UTC, levy002 commented on index.html
> +        <p>I’am a Software Developer</p>
- [ ] Kindly change this `p` to the heading `hx` tag (examples: `h1`, `h2`, `h3`, etc...) because this is a subtitle so we have to make sure that it is wrapped inside a heading tag.

2022-08-18 04:48 UTC, levy002 commented on css/styles.css
> +  }
- [ ] Kindly make sure your look exactly like the one provided on the Figma template. Please check the alignment (spacing) of the headline section and make sure it looks the same as the Figma design.
 
   - ### Your design
   
   ![image](https://user-images.githubusercontent.com/87197412/185294935-ea56926b-4eef-431a-8bff-9f7c5ed3a2cd.png)

    - ### Figma design
   
   ![image](https://user-images.githubusercontent.com/87197412/185295043-844afaf2-6458-4d44-93ca-bbd4dd9666cf.png)

2022-08-18 06:00 UTC, bekure27 commented on css/styles.css
> +  }
[@levy002](https://github.com/levy002) hello levy
thanks for your constructive feedback.
In my local machine, it is good.  It may vary depending on the pixel selected in the browser.

2022-08-18 06:12 UTC, levy002 commented on css/styles.css
> +  }
Hello, @bekure27 thanks! can you please check again the Figma template because the logo and the headline section are aligned on the same starting point according to the y-axis (vertically), but because on your side you have used `align-items: center` it is aligning the headline section in the center of the page. I have tried to make `align-items: start` and increase `margin-left` on the headline finally it was exactly the same as the Figma design. That's the reason why I've suggested that particular change!

2022-08-18 06:16 UTC, bekure27 commented on css/styles.css
> +  }
Thanks

2022-08-18 07:13 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @bekure27 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 07:13 UTC, tresorsawasawa commented on css/styles.css
> +
- [ ] As mentioned by the previous reviewer, kindly make sure your design sticks as much as possible to your chosen Figma template(e.g.: text alignment in the headline section, spacing at the left,...). If you correctly check the Figma design, you will notice that the headline section is aligned on the same starting point horizontally(i.e they all have the same spacing at the left). The problem in your design is because your `align-items` has the `center` value instead of the `flex-start` value, then you can add the correct value to `padding at the left`.

2022-08-18 07:13 UTC, tresorsawasawa commented on css/styles.css
> +@media only screen and (max-width: 600px) {
- [ **OPTIONAL** ] I think it would be better if you remove the **@media query** for now, and consider the current styling as the default styling for your whole web page(mobile version). In your next milestones, you will have the project concerning the `@media` query.

2022-08-18 07:41 UTC, bekure27 commented on index.html
> +        </ul>
[@tresorsawasawa](https://github.com/tresorsawasawa) thanks for your comment.
when i change to nav tag it generates a linter error.

2022-08-18 08:32 UTC, tresorsawasawa commented on index.html
> +        </ul>
Hi @bekure27 
What is the error message?

2022-08-18 08:40 UTC, bekure27 commented
***@***.****
*thanks I solved the problem*
*By replacing  header with nav tag.*
[image: 1.png]
can I request review

On Thu, 18 Aug 2022, 11:32 am Tresor Sawasawa, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/bekure27/project-1-portfolio/pull/1#discussion_r948811298>
> :
>
> > +            <li><a href="#" class="toggle-menu"><img src="icons/menu_icon.png" alt=""></a></li>
> +        </ul>
>
> Hi @bekure27 <https://github.com/bekure27>
> What is the error message?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bekure27/project-1-portfolio/pull/1#discussion_r948811298>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ3CVGHJJPKMB73YAUJ5IP3VZXYKFANCNFSM563FAFYQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-18 08:43 UTC, bekure27 commented on index.html
> +        </ul>
@tresorsawasawa
thanks, I solved the problem
By replacing the header with the nav tag.
![1](https://user-images.githubusercontent.com/108407448/185351633-992ba0ed-9336-4682-b508-8c6858cddb01.png)
can I request a review

2022-08-18 09:06 UTC, cynthiainga approved these changes
Hi @bekure27, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [x] No linters ✔️ 
- [ ] Good commit history ✔️ 
- [ ] Correct usage of Github flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 09:10 UTC, merged